apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::587410166417:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1CMIR5BC0BZ3N
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::587410166417:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-10-16T11:25:53Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2997"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 6c377323-4215-4fb6-b5d8-62d7c5ef65f6
